model_name: buffalo_l
# default insightface dir. Library always appends /models to it
model_dir: '~/.insightface'
detection_threshold: 0.2
device: cpu
extract:
    size: (1024, 1024)
    min_resolution: 0
    border_expand: (0., 0.)
    align: True
    maintain_proportion: False
    masked: False
    # params used when masking
    dilation_kernel: (1, 1)
    blur_size: 1