data:
  input_shape: [28, 28, 1]
  buffer_size: 5000
model:
  encoder:
    latent_dim: 100
    init_filters: 16
    num_conv_blocks: 3
    n_channels: 1
    kernel_size: 3
    strides: 2
  decoder:
    latent_dim: 100
    init_filters: 32
    num_conv_blocks: 2
    kernel_size: 3
    leaky_relu_slope: 0.2
    strides: 1 # 1 if UPSAMPLING, 2 if DECONV
    # Generator might not rely on LeakyReLU
    leaky_relu_slope: 0.2
    # UPSAMPLING, DECONV, ??PIXELSHUFFLER
    upscale_method: UPSAMPLING
training:
  # Adam for both
  learning_rate: 0.0002
  beta1: 0.5
  rmse_loss_factor: 1.
  batch_size: 128
  # how often to save model checkpoint
  checkpoint_steps: 20
  # how many examples to display during training
  plot_sample_size: 16